name: my-action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
            echo "hello world!"
            echo "from garfield ~"
      - name: print goodbye
        run: echo "goodbye world!"
